name: Run Playwright tests

on:
  push:          # runs on every push
  pull_request:  # runs on new PRs or PR updates
  schedule:
    - cron: '30 3 * * 1-5'
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Playwright shards
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.0-noble

    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1,2,3,4,5]
        shardTotal: [5]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Create .env file
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "NEW_PASSWORD=${{ secrets.NEW_PASSWORD }}" >> .env
          echo "FIRST_NAME=${{ secrets.FIRST_NAME }}" >> .env
          echo "STREET_NAME=${{ secrets.STREET_NAME }}" >> .env
          echo "CITY=${{ secrets.CITY }}" >> .env
          echo "STATE=${{ secrets.STATE }}" >> .env
          echo "COUNTRY=${{ secrets.COUNTRY }}" >> .env
          echo "ZIP_CODE=${{ secrets.ZIP_CODE }}" >> .env

      - name: Install deps
        run: npm ci

      - name: Install TestDino reporter (local tgz)
        run: npm install ./testdino-playwright-1.1.0.tgz

      - name: Run shard ${{ matrix.shardIndex }}
        run: npx playwright test --project=chromium --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}